language: python
deploy:
  true:
    condition: $TRAVIS_PYTHON_VERSION == "2.7"
    repo: tartavull/pixel
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: kzkhTZcAuSt/kUD6jzTBybKCeDxImC+0tO+M2xca5IFaIWRvwxTI12Z+XGbGPxSpg73Q/BByk9msMFKv6O9dMTZtnWRZhqi0qXtQ54bcll1+cx++n/q/Rd4aRzX0H+1NPI5d099swkkibwfVcGVJhLhvU3HkhgS0CMvmdPEPO72Vu9HYS64hZS44SDuv6KktWWs/Yu2GB2C3mzWlzenWHgkorMOF86AlTCGMm6arFhtRhEtyQb43mviLw1EsWA1cOYifbjJAWLGMYowI2X3ixlIqGTBrMiH2vUxilkHtbsKgt3kstlQ9tmGlLRpbSYsdF6unYJl3ZoRiU+FeBnTK2cCeSEor08d1fp67FKzAFu2u4W9wH4Srl8EbfMI0r0yIphkCbsnODES2tmO0AGq9edvjOp7LSQPSAC1cbZ32FetuVVM0E8P5IUVzjXLjZAmoVHeFwesqpUQQoUToH1TAuQ3doeSr1JbVlNJfMRuz8ZWUj0AliNpaIccbgbnqA8JWihzjDoqixHAfhmIpDGXZ8yCvC7IhWRf/h57E85eNrHXwBLOgMSzXmDohiCefWTRRVrkLKezERzgPvzopsklbZWY7VDvRIWOlzhuhgttG0c/yTeGa4z+DbzQt67wZIVau0d5NgTHW815EnPkYENnumD/M4clJEMjYR5Trf8MEsW8=
  provider: pypi
  user: tartavull
python:
- '2.7'
script: make test

before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-h5py
install:
- pip install -r requirements.txt
- python setup.py install